name: Build Exe
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: g++ FivemDumper.cpp -o FivemDumper.exe -static
    - name: Upload Exe
      uses: actions/upload-artifact@v4
      with:
        name: FivemDumperProgrami
        path: FivemDumper.exe
